spring:
  profiles:
    active: dev

#------------------------------------------------------------------------------------------------------------------
#Logging
#Setting up the logging level in .yml file, but it is better doing it in the XML FIle.

#logging:
#  level:
#    com:
#      Badhwar:
#        journalApp:
#          services:
#            UserService: OFF

#logging:
#  level:
#    com:
#      Badhwar:
#        journalApp: DEBUG
#mentioning level, means that specific level or more severe levels only, Trace being the lowest and Error being highest.

#Specifing Logs Level at the Root
#logging:
#  level:
#    root: ERROR

    #logging:
    #  level:
    #    root: OFF


#--------------------------------------------------------------------------------------------------------------------------------
# Creating profiles are very usual process for Development and production.
  #Multiple ways to do that:-
   #Not fixing in application.ym/properties file instead giving at the Command line, or setting config in intellij,...

#Can Make Changes to the configuration of the Intellij configuration to run until in Intellij
#spring.profiles.active=dev in Edit Configuration

#In production, when we run the jar
  # ex - java -jar ....path --spring.profiles.active=...