spring:
  application:
    name: Journal App
  main:
    allow-circular-references: true
  redis:
    host: redis-13772.c13.us-east-1-3.ec2.redns.redis-cloud.com
    port: 13772
    password: 1P2y8UjOWteeyHqluoEJDbL6BRRvU9Ec
  data:
    mongodb:
      uri: mongodb+srv://kbb914:Ronaldo07$@journal.ltwg8.mongodb.net/?retryWrites=true&w=majority&appName=Journal
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port : 587
    username: jforjacob04@gmail.com
    password: yvla agnk oiqp gopw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal
