spring:
  profiles:
    active: dev

# Creating profiles are very usual process for Development and production.
  #Multiple ways to do that:-
   #Not fixing in application.ym/properties file instead giving at the Command line, or setting config in intellij,...

#Can Make Changes to the configuration of the Intellij configuration to run until in Intellij
#spring.profiles.active=dev in Edit Configuration

#In production, when we run the jar
  # ex - java -jar ....path --spring.profiles.active=...